image: eclipse-temurin:8-jdk

stages:
  - test

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"

cache:
  key: gradle-wrapper-jdk8
  paths:
    - .gradle/caches/
    - .gradle/wrapper/

test:
  stage: test
  script:
    - ./gradlew --version
    - ./gradlew clean test check jar --console=plain -PbuildHash="$CI_COMMIT_SHA" -PrequireKnownBuildHash=true
  artifacts:
    when: always
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
    paths:
      - build/reports/tests/test/
      - build/test-results/test/
    expire_in: 1 week
  tags:
    - jdk8
